import "../styles/globals.css";
import type { AppProps } from "next/app";
import { useRouter } from "next/router";

import Head from "next/head";

import Header, { Pages } from "../components/header";
import Background from "../components/background";
import ScrollContainer from "../components/scrollContainer";

import styles from "../styles/Home.module.css";

const stateMap: { [state in Pages]: (x: number, y: number) => boolean } = {
	"/": (x, y) => Math.abs(x - 0.5) - 1 * y > 0.15,
	resume: (x, y) => x < 0.17 || x > 0.83,
	projects: (x, y) => x < 0.17 || x > 0.83,
	contact: (x, y) => x < 0.17 || x > 0.83 || y + (x - 0.5) * (x - 0.5) > 0.75,
};

const buttonMap: {
	[state in Pages]?: { buttonText: string; onClick?: () => void };
} = {
	resume: { buttonText: "View PDF" },
};

const getPage = (pathname: string) => {
	const path = pathname.substring(1) || "/";
	return path in stateMap ? (path as Pages) : "/";
};

function MyApp({ Component, pageProps }: AppProps) {
	const router = useRouter();
	const page = getPage(router.pathname);
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.googleapis.com"></link>
				<link
					rel="preconnect"
					href="https://fonts.gstatic.com"
					crossOrigin="true"
				></link>
				<link
					href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=Josefin+Sans&family=Josefin+Slab&display=swap"
					rel="stylesheet"
				></link>
			</Head>

			<main className={styles.main}>
				<ScrollContainer visible={page !== "/"} {...buttonMap[page]}>
					<Background<Pages> stateMap={stateMap} state={page} />
					<Header page={page} />
					<Component {...pageProps} />
				</ScrollContainer>
			</main>
		</div>
	);
}

export default MyApp;
