import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Header, { Pages } from "../components/header";
import Background from "../components/background";
import Card from "../components/projects/card";
import Projects from "../components/projects";

import { useState } from "react";
import ScrollContainer from "../components/scrollContainer";
import Resume from "../components/resume";
import Contact from "../components/contact";

const stateMap: { [state in Pages]: (x: number, y: number) => boolean } = {
	main_page: (x, y) => Math.abs(x - 0.5) - 1 * y > 0.15,
	resume_page: (x, y) => x < 0.17 || x > 0.83,
	projects_page: (x, y) => x < 0.17 || x > 0.83,
	contact_page: (x, y) =>
		x < 0.17 || x > 0.83 || y + (x - 0.5) * (x - 0.5) > 0.75,
};

const Home: NextPage = () => {
	const [page, setPage] = useState<Pages>("projects_page");
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.googleapis.com"></link>
				<link
					rel="preconnect"
					href="https://fonts.gstatic.com"
					crossOrigin="true"
				></link>
				<link
					href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=Josefin+Sans&family=Josefin+Slab&display=swap"
					rel="stylesheet"
				></link>
			</Head>

			<main className={styles.main}>
				<Background<Pages> stateMap={stateMap} state={page} />
				<Header page={page} setPage={setPage} />
				<ScrollContainer buttonText="View PDF">
					{/* <Projects /> */}
					{/* <Resume /> */}
					<Contact />
				</ScrollContainer>
			</main>
		</div>
	);
};

export default Home;
