import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Header, { Pages } from "../components/header";
import Background from "../components/background";

import { useState } from "react";

const Home: NextPage = () => {
	const [page, setPage] = useState<Pages>("main_page");
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.googleapis.com"></link>
				<link
					rel="preconnect"
					href="https://fonts.gstatic.com"
					crossOrigin="true"
				></link>
				<link
					href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=Josefin+Sans&family=Josefin+Slab&display=swap"
					rel="stylesheet"
				></link>
			</Head>

			<main className={styles.main}>
				{/* <AnimatedDrop posx={0} posy={0} tailPosx={-100} tailPosy={-100} /> */}
				<Background<Pages>
					stateMap={{
						main_page: (x, y) => Math.abs(x - 0.5) - 0.5 * y + 0.9 > 1,
						resume_page: (x, y) => x < 0.15 || x > 0.85,
						projects_page: (x, y) => x < 0.15 || x > 0.85,
						contact_page: (x, y) =>
							x < 0.15 || x > 0.85 || y + (x - 0.5) * (x - 0.5) > 0.75,
					}}
					state={page}
				/>
				<Header page={page} setPage={setPage} />
			</main>
		</div>
	);
};

export default Home;
