import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Header from "../components/header";

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link rel="preconnect" href="https://fonts.googleapis.com"></link>
				<link
					rel="preconnect"
					href="https://fonts.gstatic.com"
					crossOrigin="true"
				></link>
				<link
					href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=Josefin+Sans&family=Josefin+Slab&display=swap"
					rel="stylesheet"
				></link>
			</Head>

			<main className={styles.main}>
				{/* <AnimatedDrop posx={0} posy={0} tailPosx={-100} tailPosy={-100} /> */}
				<Header />
			</main>
		</div>
	);
};

export default Home;
